sudo: false
language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
notifications:
  email: true
before_script:
  - npm prune
script:
  - npm run build
after_success:
  - npm run deploy
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master